#!/bin/bash

echo "📦 Sidecar Data Collection - BATCH MENU"
echo "========================================"
echo ""
echo "Available batch collections (choose one to run):"
echo ""
echo "🏛️  OHIO BATCHES:"
echo "   ./run_ohio_batch1.sh    # 477 zip codes, ~5.3 hours"
echo "   ./run_ohio_batch2.sh    # 477 zip codes, ~5.3 hours"
echo ""
echo "🌴 FLORIDA BATCHES:"
echo "   ./run_florida_batch1.sh # 474 zip codes, ~5.3 hours"
echo "   ./run_florida_batch2.sh # 473 zip codes, ~5.2 hours"
echo ""
echo "🍑 GEORGIA BATCHES:"
echo "   ./run_georgia_batch1.sh # 304 zip codes, ~3.4 hours"
echo "   ./run_georgia_batch2.sh # 303 zip codes, ~3.4 hours"
echo ""
echo "📊 SUMMARY:"
echo "   • Each batch processes 100 drugs"
echo "   • Rate: 2.5 requests/second (SAFE - no rate limit risk)"
echo "   • Progress tracked separately for each batch"
echo "   • Can run batches in any order"
echo "   • Can run multiple batches in parallel (if desired)"
echo ""
echo "💡 RECOMMENDATION:"
echo "   Start with shortest batch first: ./run_georgia_batch1.sh"  
echo "   This gives you results in ~3.4 hours!"
echo ""
echo "🔧 MANUAL COMMANDS:"
echo "   python3 data_collection.py --states OH --batch 1 --total-batches 2"
echo "   python3 data_collection.py --states FL --batch 2 --total-batches 2"
echo "   python3 data_collection.py --states GA --batch 1 --total-batches 2" 